services:
  postgres-db:
    image: postgres:18-alpine
    container_name: postgres-lab4
    environment:
      POSTGRES_DB: lab4db
      POSTGRES_USER: ${DB_USER:-lab4user}
      POSTGRES_PASSWORD: ${DB_PASS:-lab4pass}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lab4user -d lab4db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
