apiVersion: v1
kind: Service
metadata:
  name: web-lab4-backend
  namespace: web-lab4
spec:
  type: NodePort
  selector:
    app: web-lab4-backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080

