apiVersion: v1
kind: ConfigMap
metadata:
  name: web-lab4-config
  namespace: web-lab4
data:
  application.properties: |
    spring.application.name=web_lab4
    spring.datasource.url=jdbc:postgresql://postgres-service:5432/lab4db
    spring.datasource.username=${DB_USER}
    spring.datasource.password=${DB_PASS}
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    server.port=8080

