apiVersion: v1
kind: Service
metadata:
  name: web-lab4-frontend
  namespace: web-lab4
spec:
  type: NodePort
  selector:
    app: web-lab4-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000

